version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/birdgame
      - SECRET_KEY=devsecret
      - FLASK_ENV=development
    depends_on:
      - mongodb